[2025-04-29T09:32:30.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T09:32:30.580+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow.spark_wordcount manual__2025-04-29T09:32:28.080112+00:00 [queued]>
[2025-04-29T09:32:30.590+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow.spark_wordcount manual__2025-04-29T09:32:28.080112+00:00 [queued]>
[2025-04-29T09:32:30.591+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-29T09:32:30.606+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): spark_wordcount> on 2025-04-29 09:32:28.080112+00:00
[2025-04-29T09:32:30.613+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-29T09:32:30.615+0000] {standard_task_runner.py:72} INFO - Started process 284 to run task
[2025-04-29T09:32:30.616+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_***', 'spark_wordcount', 'manual__2025-04-29T09:32:28.080112+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpme1ka18h']
[2025-04-29T09:32:30.619+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask spark_wordcount
[2025-04-29T09:32:30.671+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_airflow.spark_wordcount manual__2025-04-29T09:32:28.080112+00:00 [running]> on host e081cd3880a4
[2025-04-29T09:32:30.771+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***' AIRFLOW_CTX_TASK_ID='spark_wordcount' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T09:32:28.080112+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T09:32:28.080112+00:00'
[2025-04-29T09:32:30.778+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/openlineage/plugins/listener.py:477: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-29T09:32:30.803+0000] {client.py:121} INFO - OpenLineageClient will use `http` transport
[2025-04-29T09:32:31.038+0000] {adapter.py:162} INFO - Successfully emitted OpenLineage `START` event of id `019680e4-0030-79bd-a3a3-c9ac1084020d`
[2025-04-29T09:32:31.075+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T09:32:31.088+0000] {base.py:84} INFO - Retrieving connection 'spark_connection'
[2025-04-29T09:32:31.090+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://sparkflow-spark-master:7077 --num-executors 2 --total-executor-cores 4 --executor-cores 2 --executor-memory 4G --driver-memory 4G --name spark_wordcount --deploy-mode client ./jobs/wordcount.py
[2025-04-29T09:32:31.144+0000] {spark_submit.py:644} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-29T09:32:31.145+0000] {spark_submit.py:644} INFO - JAVA_HOME is not set
[2025-04-29T09:32:31.154+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://sparkflow-spark-master:7077 --num-executors 2 --total-executor-cores 4 --executor-cores 2 --executor-memory 4G --driver-memory 4G --name spark_wordcount --deploy-mode client ./jobs/wordcount.py. Error code is: 1.
[2025-04-29T09:32:31.167+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/openlineage/plugins/listener.py:477: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-29T09:32:31.179+0000] {client.py:121} INFO - OpenLineageClient will use `http` transport
[2025-04-29T09:32:31.420+0000] {adapter.py:162} INFO - Successfully emitted OpenLineage `FAIL` event of id `019680e4-0030-79bd-a3a3-c9ac1084020d`
[2025-04-29T09:32:31.464+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=spark_***, task_id=spark_wordcount, run_id=manual__2025-04-29T09:32:28.080112+00:00, execution_date=20250429T093228, start_date=20250429T093230, end_date=20250429T093231
[2025-04-29T09:32:31.493+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-29T09:32:31.495+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task spark_wordcount (Cannot execute: spark-submit --master spark://sparkflow-spark-master:7077 --num-executors 2 --total-executor-cores 4 --executor-cores 2 --executor-memory 4G --driver-memory 4G --name spark_wordcount --deploy-mode client ./jobs/wordcount.py. Error code is: 1.; 284)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://sparkflow-spark-master:7077 --num-executors 2 --total-executor-cores 4 --executor-cores 2 --executor-memory 4G --driver-memory 4G --name spark_wordcount --deploy-mode client ./jobs/wordcount.py. Error code is: 1.
[2025-04-29T09:32:31.520+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-29T09:32:31.534+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T09:32:31.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
